### ISSUE TITLE
Application keeps stopping

### ISSUE THREAD

**Issue by drdoof2019** [vknow360/CustomWebView#19]
Application keeps stopping for devices under API version 25 because of CustomWebView.
Here is [topic](https://community.appinventor.mit.edu/t/app-keeps-stopping-on-some-devices/56205/6)

**Comment by vknow360** [comment]
https://community.appinventor.mit.edu/t/app-keeps-stopping-on-some-devices-when-using-custom-webview/56205/12?u=vknow360
