### ISSUE TITLE
Kodular - Permission Issue

### ISSUE THREAD

**Issue by arthaswow** [vknow360/CustomWebView#2]
If a website requires access to camera or microfone this two permissions are needed, 
```
android.webkit.resource.VIDEO_CAPTURE
android.webkit.resource.AUDIO_CAPTURE
```
 webview raise the PermissionRequest but cant grant this two "missing grant permision blocks from version 4

**Comment by vknow360** [comment]
Thank you for reporting bug.
I shall try to fix it as soon as possible.

**Comment by vknow360** [comment]
I have updated extension and added missing permissions.
Let me know if it still does not works.
Thank you.

**Comment by arthaswow** [comment]
thanks for the update
