### ISSUE TITLE
Not work form file

### ISSUE THREAD

**Issue by JEB67** [vknow360/CustomWebView#24]
the web site OK but when I click on select file form not work. I remember that this worked without problems since I developed an app before and if it worked. Could it be that we have to use another extension? Help please (urgent!!)
Hola!!, necesito ayuda. Uso la extensión CustomWebView en inventor, veo el sitio web bien, pero cuando hago clic en el formulario de selección de archivo no funciona. Recuerdo que esto funcionó sin problemas ya que desarrollé una aplicación antes y si funcionó. ¿Será que tengo que usar otra extensión? Ayuda por favor (¡urgente!!)

**Comment by vknow360** [comment]
Hey, 
You will have to pick file using activity starter and then pass path to the extension.
Here you can find blocks for that:
https://community.appinventor.mit.edu/t/problem-viewing-web-page-on-custom-web-view/29615/12?u=vknow360
