### ISSUE TITLE
JS Alert causes WebView to freeze

### ISSUE THREAD

**Issue by lExplLicit** [vknow360/CustomWebView#32]
Hello, first of all, thanks for this wonderful extension.

i am experiencing a problem, that whenever my web application calls an JS Alert, the WebView completely freezes.
Even when using the function blocks OnJsAlert & DismissJsAlert like in the screenshot below, i need to completely close the app to continue using the browser.

![image](https://github.com/vknow360/CustomWebView/assets/54572942/dc4d6809-487b-494b-adbd-4aba6ce47a8b)

According to https://community.appinventor.mit.edu/t/alert-function-custom-webview/61882/10 and other forum posts, i am not the only one with this issue.

ADB is not very helpful (i think):

![image](https://github.com/vknow360/CustomWebView/assets/54572942/89fb913a-2493-4b0f-8882-23b4de61af3c)

Would be great if this issue could easily be fixed. Thanks!

**Comment by vknow360** [comment]
For some unknown reason, dismissing JS alert immediately doesn't work.
Instead if you show a notifier message to the user and then dismiss, it'll work fine.
Please have a look:
https://community.appinventor.mit.edu/t/customwebview-an-extended-form-of-web-viewer/9934/309?u=vknow360

**Comment by lExplLicit** [comment]
Thanks! This workaround works perfectly:

![image](https://github.com/vknow360/CustomWebView/assets/54572942/724c00a2-b626-4556-8d86-e5a77075a508)

I first tried with a "Message Dialog" which does not work. Using "Choose Dialog" does.

Issue closed.
