### ISSUE TITLE
Request for API upgrade.

### ISSUE THREAD

**Issue by followtolight** [vknow360/CustomWebView#33]
Hello!   First of all, I would like to express my sincere gratitude for this project, as it has provided me with significant convenience and serves as an excellent extension.
However, the current API required for this extension is 21, which is somewhat outdated for the latest Android version.   I was wondering if there is any plan to create a higher version?   I'm not sure if this would be a lot of trouble, But I still want to ask.Thank you.

**Comment by vknow360** [comment]
That is min sdk required to use CustomWebView.
It has nothing to do with target sdk.
