### ISSUE TITLE
Deeplink NOT SUPPORTING

### ISSUE THREAD

**Issue by theadp** [vknow360/CustomWebView#9]
I am using version 10,when i click Whatsapp share button in my website through app it is not opening anything
![blocks (3)](https://user-images.githubusercontent.com/68984419/107475209-c8534200-6b99-11eb-8bd0-626f2386aeb9.png)

**Comment by vknow360** [comment]
Hi @theadp 
Thanks for reporting the bug.
Can you try with beta version?
https://github.com/vknow360/CustomWebView/tree/beta

**Comment by vknow360** [comment]
Does beta version work?
